version: '3.1'

services:
  nginx:
    build: ./nginx
    volumes:
      - .templates:/etc/nginx/templates
    restart: always
    environment:
      - NGINX_PORT=80
    image: michaeltkachenko/michael-tkachenko-nginx:latest
    ports:
      - 8080:80

  ubuntu:
    build: ./ubuntu
    restart: always
    image: michaeltkachenko/michael-tkachenko-ubuntu:latest
    ports:
      - 9090:80